name: MCEmojis
version: 1.0
api-version: 1.17
main: me.weisboys.mcemojis.MCEmojis
commands:
    mcemojis:
        description: main command for mcemojis
        usage: /<command> [subcommand] ...
        permission: mcemojis.emojiscommand
        
permissions:
    mcemojis.list: 
        description: the permission to list available emojis
        default: true
    mcemojis.reload: 
        description: the permission to reload the mcemojis plugin
        default: op
    mcemojis.spam:
        description: the permission to spam your wonderful face with ALL the emojis EVER
        default: true
    mcemojis.search:
        description: the permission to search for a specifc emoji
        default: true    
    mcemojis.help:
        description: the permission to show help and command list
        default: true
    mcemojis.favorites:
        description: the permission to view and add to the favorites list
        default: true    